server:
  port: 8010
  servlet:
    session:
      timeout: 120s

spring:
  application:
    name: mcp-sse-server
  ai:
    mcp:
      server:
        annotation-scanner:
          enabled: true
        type: ASYNC
        sse-message-endpoint: /mcp/messages
        enabled: true
